# --- Sieve (mail filtering) --------------------------------------------------
plugin {
  sieve = file:/var/mail/vhosts/%d/%n/sieve;active=/var/mail/vhosts/%d/%n/.dovecot.sieve

  # Applied to every user before their personal script. Files spam into Junk.
  sieve_default = /etc/dovecot/sieve/default.sieve
  sieve_default_name = system

  sieve_extensions = +editheader
}
