# Generated by Django 5.2.14 on 2026-06-01 21:35

import django.db.models.deletion
import django.utils.timezone
import mail.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "dkim_selector",
                    models.CharField(blank=True, default="mail", max_length=63),
                ),
                ("dkim_private_key", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Mailbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("full_name", models.CharField(blank=True, max_length=255)),
                ("quota_bytes", models.BigIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mailboxes",
                        to="mail.domain",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "mailboxes",
                "ordering": ["email"],
            },
            managers=[
                ("objects", mail.managers.MailboxManager()),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "folder",
                    models.CharField(
                        choices=[
                            ("INBOX", "Inbox"),
                            ("SENT", "Sent"),
                            ("DRAFTS", "Drafts"),
                            ("JUNK", "Junk"),
                            ("TRASH", "Trash"),
                            ("ARCHIVE", "Archive"),
                        ],
                        default="INBOX",
                        max_length=16,
                    ),
                ),
                (
                    "message_id",
                    models.CharField(blank=True, db_index=True, max_length=998),
                ),
                ("in_reply_to", models.CharField(blank=True, max_length=998)),
                ("from_addr", models.CharField(blank=True, max_length=998)),
                ("to_addrs", models.TextField(blank=True)),
                ("cc_addrs", models.TextField(blank=True)),
                ("subject", models.CharField(blank=True, max_length=998)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("body_text", models.TextField(blank=True)),
                ("body_html", models.TextField(blank=True)),
                ("eml", models.FileField(blank=True, upload_to="messages/%Y/%m/")),
                ("size", models.PositiveBigIntegerField(default=0)),
                ("is_read", models.BooleanField(default=False)),
                ("is_flagged", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mailbox",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=255)),
                ("size", models.PositiveBigIntegerField(default=0)),
                ("file", models.FileField(upload_to="attachments/%Y/%m/")),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="mail.message",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Alias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=255)),
                ("destination", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="mail.domain",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "aliases",
                "ordering": ["source"],
                "unique_together": {("source", "destination")},
            },
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["mailbox", "folder", "-date"],
                name="mail_messag_mailbox_fd34ed_idx",
            ),
        ),
    ]
