# Generated by Django 5.2.14 on 2026-06-01 21:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutboundMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mail_from", models.CharField(blank=True, max_length=998)),
                (
                    "recipients",
                    models.TextField(help_text="Comma-separated envelope recipients"),
                ),
                ("raw", models.FileField(upload_to="queue/%Y/%m/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                        ],
                        default="QUEUED",
                        max_length=8,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=10)),
                ("last_error", models.TextField(blank=True)),
                (
                    "next_attempt",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["next_attempt"],
            },
        ),
        migrations.AddField(
            model_name="mailbox",
            name="signature",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="mailbox",
            name="spam_threshold",
            field=models.FloatField(
                default=5.0, help_text="Messages scoring at/above this go to Junk"
            ),
        ),
        migrations.AddField(
            model_name="mailbox",
            name="vacation_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mailbox",
            name="vacation_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="mailbox",
            name="vacation_subject",
            field=models.CharField(blank=True, default="Out of office", max_length=255),
        ),
        migrations.AddField(
            model_name="message",
            name="is_spam",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="references",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="message",
            name="spam_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="message",
            name="thread_id",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.CreateModel(
            name="Filter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=128)),
                ("priority", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "field",
                    models.CharField(
                        choices=[
                            ("FROM", "From"),
                            ("TO", "To/Cc"),
                            ("SUBJECT", "Subject"),
                            ("BODY", "Body"),
                            ("ANY", "Anywhere"),
                        ],
                        default="FROM",
                        max_length=16,
                    ),
                ),
                (
                    "match",
                    models.CharField(
                        choices=[
                            ("CONTAINS", "contains"),
                            ("EQUALS", "equals"),
                            ("STARTSWITH", "starts with"),
                            ("REGEX", "matches regex"),
                        ],
                        default="CONTAINS",
                        max_length=16,
                    ),
                ),
                ("value", models.CharField(max_length=512)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("MOVE", "Move to folder"),
                            ("LABEL", "Apply label"),
                            ("READ", "Mark as read"),
                            ("STAR", "Flag/star"),
                            ("SPAM", "Mark as spam (Junk)"),
                            ("DELETE", "Move to Trash"),
                        ],
                        default="MOVE",
                        max_length=16,
                    ),
                ),
                (
                    "action_arg",
                    models.CharField(
                        blank=True,
                        help_text="Folder name or label name",
                        max_length=128,
                    ),
                ),
                (
                    "mailbox",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "id"],
            },
        ),
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("color", models.CharField(default="#6b7280", max_length=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mailbox",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="message",
            name="labels",
            field=models.ManyToManyField(
                blank=True, related_name="messages", to="mail.label"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["mailbox", "thread_id"], name="mail_messag_mailbox_ee25c6_idx"
            ),
        ),
        migrations.AddField(
            model_name="outboundmessage",
            name="sender_mailbox",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="outbound",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="label",
            unique_together={("mailbox", "name")},
        ),
    ]
