# Generated by Django 5.2.14 on 2026-06-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0004_contact_uid_contact_updated_at_mailbox_webhook_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="category",
            field=models.CharField(
                choices=[
                    ("PRIMARY", "Primary"),
                    ("SOCIAL", "Social"),
                    ("PROMOTIONS", "Promotions"),
                    ("UPDATES", "Updates"),
                    ("FORUMS", "Forums"),
                ],
                db_index=True,
                default="PRIMARY",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="is_important",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="is_muted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="snooze_until",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="outboundmessage",
            name="scheduled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["mailbox", "folder", "category", "-date"],
                name="mail_messag_mailbox_ba8904_idx",
            ),
        ),
    ]
